### ISSUE TITLE
Update to Angular 15

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/ui-toolkit-angular#439]
**Describe the bug** 🪲

**To Reproduce** 🪜

**Expected behavior**

**Screenshots** 🖼️

**Browser Information (please complete the following information):** 🖥️
 - OS: [e.g. Windows 10 build 21H1, Ubuntu 20.04 LTS]
 - Browser and Version: [e.g. IE Edge 95.0.1020.40 ]

**Additional context**

**Comment by madhavilosetty-intel** [comment]
Fixed it as part of the PR #476
